### ISSUE TITLE
How to turn off all funky stuff... no brace matching, no auto-completion, just want basic mode

### ISSUE THREAD

**Issue by infradig** [daanx/isocline#10]
Title says it all. I can't find anything.

Also, on a light themed terminal the default grays are just unreadable. I can't find any documentation on how to chnage that.

**Comment by flexoron** [comment]
I guess some hints are found in isocline.c for example:
ic_enable_brace_matching(false);
ic_enable_brace_insertion(false);
ic_enable_completion_preview(false);
ic_enable_color(false);

and it seems that NULLs disable functionality as well (I don't get bus errors or segfaults so far)
ic_set_default_completer(NULL, NULL);
ic_set_default_highlighter(NULL, NULL);

**Comment by infradig** [comment]
Thanks.

**Comment by infradig** [comment]
I am now using ISOCLINE as the default in https://github.com/trealla-prolog/trealla

Thanks

**Comment by daanx** [comment]
Yes, the header file shows these options best, see <https://github.com/daanx/isocline/blob/main/include/isocline.h#L315>

Trealla looks like a fun project -- let me know if you find further issues.
