### ISSUE TITLE
Haskell: 100 % cpu usage using: putFmtLn ““

### ISSUE THREAD

**Issue by rpxrpxrpx** [daanx/isocline#7]
Hi.

Using the Haskell command

`putFmtLn ““`

(Parameter is an empty String) my cpu usage goes up to 100 % and I have to kill the programm using another terminal. My intention was to write an empty line to the terminal.

Tested with:
ghc 8.8.4 (debian, PPC64 cpu)
ghc 8.4.4 (debian, x86-64 cpu)

Thank you for reading this.

Edit: Corrected ghc versions.

**Comment by daanx** [comment]
Ouch -- embarrassing; just pushed a fix.

**Comment by daanx** [comment]
Updated the package to v1.0.8 as well -- let me know if it works for you
